<script setup>
    import ProfilePage from '../../components/ProfilePage.vue';
    import { useUserStore } from '../../stores/user.js';
    import { ref } from 'vue';
    import { open, save as saveDialog } from '@tauri-apps/plugin-dialog';
    import { useDbLibSync } from '../../composables/useDbLibSync.js';

    const userStore = useUserStore()
    const visibleSettings = ref(JSON.parse(JSON.stringify(userStore.$state)))

    const reset = async () =>
    {
        await userStore.loadSettings()
        visibleSettings.value = JSON.parse(JSON.stringify(userStore.$state))
    }

    const save = async () =>
    {
        userStore.$patch(JSON.parse(JSON.stringify(visibleSettings.value)))
        await userStore.saveSettings()
    }

    const chooseRepositoryPath = async () =>
    {
        const file = await open({
            multiple: false,
            directory: true,
        });

        visibleSettings.value.repository.path = file
    }

    const { status: dblibStatus, syncDbLib } = useDbLibSync()

    const chooseDbLibPath = async () =>
    {
        const file = await saveDialog({
            defaultPath: visibleSettings.value.database.dblibPath || 'onyks_bloodstone.DbLib',
            filters: [{ name: 'Altium Database Library', extensions: ['DbLib'] }]
        });

        if(file)
        {
            visibleSettings.value.database.dblibPath = file
        }
    }

    const updateDbLibNow = async () =>
    {
        await save()
        await syncDbLib()
    }

    const formatTime = (date) => date ? date.toLocaleString() : 'never'
</script>

<template>
    <ProfilePage title="Settings">

        <onyks-container type="grid" cols="2" gap="l" padding="">
            <onyks-text size="m">Login</onyks-text>
            <onyks-textfield size="m" v-model="visibleSettings.login" placeholder="e.g admin"></onyks-textfield>
            <onyks-text size="m" >Password</onyks-text>
            <onyks-textfield size="m" type="password" v-model="visibleSettings.password" placeholder="e.g admin"></onyks-textfield>
        </onyks-container>

        <onyks-header level="4">Web Manager</onyks-header>

        <onyks-container type="grid" cols="2" gap="l" padding="">
            <onyks-text size="m">Address</onyks-text>
            <onyks-textfield size="m" v-model="visibleSettings.webManagerAddress" placeholder="e.g http://192.168.1.10:8113"></onyks-textfield>
        </onyks-container>

        <onyks-header level="4">Database</onyks-header>

        <onyks-text size="s">
            The Altium .DbLib file is generated by the server from the current state of the database.
            With autoupdate on, the program checks it periodically and rewrites the local file only when
            something changed, e.g. a new category table was added. Your login is filled in the first time;
            the connection string already in the file (including a password you typed there) is kept.
            Keep the file outside the repository folder, otherwise Push would commit it.
        </onyks-text>

        <onyks-container type="grid" cols="2" gap="l" padding="">
            <onyks-text size="m">DbLib File Path</onyks-text>
            <onyks-textfield size="m" v-model="visibleSettings.database.dblibPath" placeholder="e.g C:/User/onyks_bloodstone.DbLib" disabled></onyks-textfield>
        </onyks-container>

        <onyks-container gap="m" type="group" align="center" justify="end" padding="">
            <onyks-button background="yellow" @click="chooseDbLibPath">Select</onyks-button>
        </onyks-container>

        <onyks-container type="grid" cols="2" gap="l" padding="">
            <onyks-text size="m">Autoupdate</onyks-text>
            <onyks-checkbox size="l" :checked="visibleSettings.database.autoupdate" @click="() => {visibleSettings.database.autoupdate = !visibleSettings.database.autoupdate}"></onyks-checkbox>
        </onyks-container>

        <onyks-container type="grid" cols="2" gap="l" padding="">
            <onyks-text size="m">Autoupdate Interval (in minutes)</onyks-text>
            <onyks-textfield placeholder="e.g 5" size="m" type="number" v-model="visibleSettings.database.autoupdateInterval" :disabled="!visibleSettings.database.autoupdate"></onyks-textfield>
        </onyks-container>
        <onyks-container gap="m" type="group" align="center" justify="end" padding="">
            <onyks-text size="s">Min. value of the interval is 1 minute.</onyks-text>
        </onyks-container>

        <onyks-container gap="m" type="group" align="center" justify="end" padding="">
            <onyks-text size="s">
                Last check: {{ formatTime(dblibStatus.lastCheck) }} · Last change: {{ formatTime(dblibStatus.lastChange) }}
            </onyks-text>
            <onyks-button background="blue" @click="updateDbLibNow" :disabled="dblibStatus.running">Update now</onyks-button>
        </onyks-container>

        <onyks-alert v-if="dblibStatus.error" type="error">{{ dblibStatus.error }}</onyks-alert>

        <onyks-header level="4">Repository</onyks-header>

        <onyks-container type="grid" cols="2" gap="l" padding="">
            <onyks-text size="m">Address</onyks-text>
            <onyks-textfield size="m" v-model="visibleSettings.repository.address" placeholder="e.g https://google.com"></onyks-textfield>
            <onyks-text size="m">Autoupdate</onyks-text>
            <onyks-checkbox size="l" :checked="visibleSettings.repository.autoupdate" @click="() => {visibleSettings.repository.autoupdate = !visibleSettings.repository.autoupdate}"></onyks-checkbox>
            <onyks-text size="m">Folder Path</onyks-text>
            <onyks-textfield size="m" v-model="visibleSettings.repository.path" placeholder="e.g C:/User/repository" disabled></onyks-textfield>
        </onyks-container>

        <onyks-container gap="m" type="group" align="center" justify="end" padding="">
            <onyks-button background="yellow" @click="chooseRepositoryPath">Select</onyks-button>
        </onyks-container>

        <onyks-container type="grid" cols="2" gap="l" padding="">
            <onyks-text size="m">Autoupdate Interval (in minutes)</onyks-text>
            <onyks-textfield size="m" placeholder="e.g 5" type="number" v-model="visibleSettings.repository.autoupdateInterval" :disabled="!visibleSettings.repository.autoupdate"></onyks-textfield>
        </onyks-container>
        <onyks-container gap="m" type="group" align="center" justify="end" padding="">
            <onyks-text size="s">Min. value of the interval is 1 minute.</onyks-text>
        </onyks-container>
        
        
        <onyks-container gap="m" type="group" align="center" justify="end" padding="">
            <onyks-button background="green" @click="save">Save</onyks-button>
            <onyks-button background="red" @click="reset">Reset</onyks-button>
        </onyks-container>

        <onyks-container gap="m" type="group" align="center" justify="end" padding="s">
        </onyks-container>
    </ProfilePage>
</template>

<style scoped>
    onyks-text
    {
        align-self: center;
    }

    onyks-textfield
    {
        width: 100%;
    }

    onyks-button
    {
        width: 120px;
    }

    onyks-checkbox
    {
        width: fit-content;
    }
</style>